config/routes.rb
Rails.application.routes.draw do
  resources :users, except: :index do
    get 'student'
    get 'mentor'
    resources :topics, only: [:create]
    resources :feedbacks, only: [:index]
  end

  resources :pairings, except: :show do
    resources :feedbacks, only: [:new, :create]
  end

  post '/sessions' => 'sessions#new'
  delete '/sessions' => 'sessions#destroy', as: 'logout'
  root 'users#show'
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :mentor_pairings, class_name: "Pairing", foreign_key: :mentor_id
  has_many :student_pairings, class_name: "Pairing", foreign_key: :student_id

  has_many :feedbacks

  has_many :mentor_feedbacks, through: :mentor_pairings, source: :feedbacks
  has_many :student_feedbacks, through: :student_pairings, source: :feedbacks

  has_many :topics_users, foreign_key: :mentor_id
  has_many :topics, through: :topics_users

  validates :name, :email, :phase, presence: true
  validates :email, uniqueness: true

  has_secure_password

  def given_mentor_feedbacks
    self.mentor_feedbacks.where(user_id: self.id)
  end

  def received_mentor_feedbacks
    self.mentor_feedbacks.where("user_id != #{self.id}")
  end

  def given_student_feedbacks
    self.student_feedbacks.where(user_id: self.id)
  end

  def received_student_feedbacks
    self.student_feedbacks.where("user_id != #{self.id}")
  end

  def average
    mentor_ratings.inject{ |sum, rating| sum + rating }.to_f / mentor_ratings.size
  end

  def sort
    self.sort { |a,b| a.pairing.start_at <=> b.pairing.start_at }
  end

  def mentor_ratings
    feedback_arr =self.mentor_feedbacks.where("user_id != #{self.id}")
    return feedback_arr.map { |feedback| feedback.rating }
  end

  def show_topics
    self.topics.map { |topic| topic.topic }.join(', ')
  end

  def unrated?
    self.mentor_ratings.empty?
  end

  def only_student?
    self.phase == 1
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, except: [:new, :create]
  def show
    redirect_to pairings_path
  end

  def student
    @upcoming_student_pairings = Pairing.upcoming_student_pairings(current_user)
    @previous_student_pairings = Pairing.previous_student_pairings(current_user)
    @feedbacks = @user.received_student_feedbacks.limit(5)
  end

  def mentor
    @upcoming_mentor_pairings = Pairing.upcoming_mentor_pairings(current_user)
    @previous_mentor_pairings = Pairing.previous_mentor_pairings(current_user)
    @topics = Topic.all.limit(10)
    @feedbacks = @user.received_mentor_feedbacks.limit(5)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(name: user_params[:name], email: user_params[:email], password: user_params[:password], phase: params[:phase])
    if @user.save
      UserMailer.welcome_email(@user).deliver_now
      session[:user_id] = @user.id
      redirect_to @user
    else
      @errors = @user.errors.full_messages
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    redirect_to 'users#new'
  end

  private
  def set_user
    if current_user
      @user ||= current_user
    else
      redirect_to new_user_path
    end
  end
  def user_params
    params.require(:user).permit(:name, :email, :password, :phase)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def display_rating(user)
    if user.unrated?
      "unrated"
    else
      user.average
    end
  end

  def display_student(user)
    if !user
      "this could be you"
    else
      user.name
    end
  end
end

app/views/users/_errors.erb
<% if @errors %>
  <% @errors.each do |error| %>
    <%= error %><br>
  <% end %>
<% end %>

app/views/users/_errors.html.erb
<% if @errors %>
  <% @errors.each do |error| %>
    <%= error %><br>
  <% end %>
<% end %>

app/views/users/mentor.html.erb
<div class='list'>
  <h1><%= current_user.name.capitalize %>'s Upcoming Mentor Pairings</h1>
  <%= link_to 'Schedule a Pairing', new_pairing_path, class: 'btn' %>
    <%= render @upcoming_mentor_pairings %>

  <h1><%= current_user.name.capitalize %>'s Previous Mentor Pairings</h1>
    <%= render @previous_mentor_pairings %>
</div>

<%= form_tag user_topics_path, class: 'topics-form' do %>
  <%= render @topics %><br>
  <%= submit_tag 'Save', class: 'btn', name: nil %>
<% end %>

<div class='list'>
  <h2>Recent Received Feedback:</h2>
  <ul>
    <%= render @feedbacks %>
  </ul>
  <%= link_to 'Your Feedback', user_feedbacks_path, class: 'btn' %>
</div>

app/views/users/new.html.erb
<div class='list'>
  <%= render 'users/errors' %>

  <h2>Login:</h2>
  <%= form_for @user, url: sessions_path do |f| %>

    <%= f.label :email %>
      <%= f.email_field :email %><br>
    <%= f.label :password %>
      <%= f.password_field :password %><br>

    <%= f.submit "Login", name: nil %>
  <% end %><br><br>

  <h2>Register:</h2>
  <%= form_for @user do |f| %>
    <p>
      <%= f.label :name %>
        <%= f.text_field :name %><br>

      <%= f.label :email %>
        <%= f.email_field :email %><br>

      <%= f.label :password %>
        <%= f.password_field :password %><br>

          <input name='phase' value='1' id='radio' type='radio'>
          <label for='radio'>Phase 1</label>

          <input name='phase' value='2' id='radio2' type='radio'>
          <label for='radio2'>Phase 2</label>

          <input name='phase' value='3' id='radio3' type='radio'>
          <label for='radio3'>Phase 3</label><br><br>


        <%#= f.label(:phase, "Phase 1") %>
      <%#= f.radio_button(:phase, "1") %><!-- <br> -->
        <%#= f.label(:phase, "Phase 2") %>
      <!-- <%#= f.radio_button(:phase, "2") %><br> -->
        <%#= f.label(:phase, "Phase 3") %>
      <!-- <%#= f.radio_button(:phase, "3") %><br> -->

      <%= f.submit "Create", name: nil %>

  <% end %>
</div>

app/views/users/student.html.erb
<div class='list'>
  <h1><%= current_user.name.capitalize %>'s Upcoming Student Pairings</h1>
    <%= render @upcoming_student_pairings %>

  <h1><%= current_user.name.capitalize %>'s Previous Student Pairings</h1>
    <%= render @previous_student_pairings %>
</div>

<div class='list'>
  <h2>Recent Received Feedback:</h2>
  <ul>
    <%= render @feedbacks %>
  </ul>
  <%= link_to 'Your Feedback', user_feedbacks_path, class: 'btn' %>
</div>