config/routes.rb
Rails.application.routes.draw do
  resources :users, except: :index do
    get 'student'
    get 'mentor'
    resources :topics, only: [:create]
    resources :feedbacks, only: [:index]
  end

  resources :pairings, except: :show do
    resources :feedbacks, only: [:new, :create]
  end

  post '/sessions' => 'sessions#new'
  delete '/sessions' => 'sessions#destroy', as: 'logout'
  root 'users#show'
end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
  belongs_to :pairing
  belongs_to :user
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  before_action :set_user
  def index
    @received_student_feedbacks = @user.received_student_feedbacks
    @received_mentor_feedbacks = @user.received_mentor_feedbacks
    @given_student_feedbacks = @user.given_student_feedbacks
    @given_mentor_feedbacks = @user.given_mentor_feedbacks
  end

  def create
    feedback = @user.feedbacks.new(feedback_params.merge(rating: params[:rating]).merge(pairing_id: params[:pairing_id]))

    if feedback.save
      redirect_to @user
    else
      @errors = feedback.errors.full_messages
      render new_user_pairing_feedback_path
    end
  end

  def new
    @feedback = Feedback.new
  end

  private
  def feedback_params
    params.require(:feedback).permit(:pairing_id, :comment, :rating)
  end
end

app/views/feedbacks/_feedback.html.erb
<li><%= feedback.comment %></li>

app/views/feedbacks/index.html.erb
<div class='list'>
  <h2>Received Feedback</h2>
  <% if !@received_student_feedbacks.empty? %>
    <% if !current_user.only_student? %>
      <h3>...as a student:</h3>
    <% end %>
    <ul>
      <%= render @received_student_feedbacks %>
    </ul>
  <% end %>
  <% if !@received_mentor_feedbacks.empty? %>
    <h3>...as a mentor:</h3>
    <ul>
      <%= render @received_mentor_feedbacks %>
    </ul>
  <% end %>
</div>

<div class='list'>
  <h2>Given Feedback</h2>
  <% if !@given_student_feedbacks.empty? %>
    <% if !current_user.only_student? %>
      <h3>...as a student:</h3>
    <% end %>
    <ul>
      <%= render @given_student_feedbacks %>
    </ul>
  <% end %>
  <% if !@given_mentor_feedbacks.empty? %>
    <h3>...as a mentor:</h3>
    <ul>
      <%= render @given_mentor_feedbacks %>
    </ul>
  <% end %>
</div>

app/views/feedbacks/new.html.erb
<div class='list'>
    <%= form_for :feedback, url: pairing_feedbacks_path do |f| %>
        <%= f.label :comment, 'Leave ASK Feedback' %>
        <%= f.text_field :comment %><br>

        <input name='rating' value='1' id='radio' type='radio'>
        <label for='radio'>1</label>

        <input name='rating' value='2' id='radio2' type='radio'>
        <label for='radio2'>2</label>

        <input name='rating' value='3' id='radio3' type='radio'>
        <label for='radio3'>3</label>

        <input name='rating' value='4' id='radio4' type='radio'>
        <label for='radio4'>4</label>

        <input name='rating' value='5' id='radio5' type='radio'>
        <label for='radio5'>5</label>

        <input type='hidden' name='pairing_id' value="#{params[:id]}">

        <%= f.submit class: 'btn' %>
    <% end %>
</div>