config/routes.rb
Rails.application.routes.draw do
  resources :users, except: :index do
    get 'student'
    get 'mentor'
    resources :topics, only: [:create]
    resources :feedbacks, only: [:index]
  end

  resources :pairings, except: :show do
    resources :feedbacks, only: [:new, :create]
  end

  post '/sessions' => 'sessions#new'
  delete '/sessions' => 'sessions#destroy', as: 'logout'
  root 'users#show'
end

app/models/pairing.rb
class Pairing < ActiveRecord::Base
  has_many :feedbacks
  belongs_to :mentor, class_name: "User", foreign_key: :mentor_id
  belongs_to :student, class_name: "User", foreign_key: :student_id

  attr_writer :start_time_text

  validate :check_start_time_text

  before_save :save_start_time_text

  def start_time_text
    @start_time_text || start_time.try(:strftime, "%Y-%m-%d %H:%M:%S")
  end

  def save_start_time_text
    self.start_time = Time.zone.parse(@start_time_text) if @start_time_text.present?
  end

  # this custom validation does not work...why?
  def check_start_time_text
    if @start_time_text.present? && Time.zone.parse(@start_time_text).nil?
      errors.add :start_time_text, "cannot be parsed"
    end
    rescue ArgumentError
      errors.add :start_time_text, "is out of range"
  end

  def self.available_pairings(user)
    self.where("start_time >= '#{(Time.now).utc.iso8601}'").where(student_id: nil).where("mentor_id != #{user.id}")
  end

  def self.previous_mentor_pairings(user)
    self.where("start_time <= '#{(Time.now).utc.iso8601}'").where(mentor_id: user.id)
  end

  def self.upcoming_mentor_pairings(user)
    self.where("start_time >= '#{(Time.now).utc.iso8601}'").where(mentor_id: user.id)
  end

  def self.previous_student_pairings(user)
    self.where("start_time <= '#{(Time.now).utc.iso8601}'").where(student_id: user.id)
  end

  def self.upcoming_student_pairings(user)
    self.where("start_time >= '#{(Time.now).utc.iso8601}'").where(student_id: user.id)
  end

end

app/controllers/pairings_controller.rb
class PairingsController < ApplicationController
  before_action :set_user
  def index
    @available_pairings =  Pairing.available_pairings(current_user).order(start_time: :desc)
  end

  def new
    @pairing = Pairing.new
  end

  def create
    @pairing = Pairing.new(pairing_params.merge(mentor_id: current_user.id))
    if @pairing.save
      redirect_to pairings_path
    else
      render 'new'
    end
  end

  def edit
    @pairing = Pairing.find(params[:id])
  end

  def update
    @pairing = Pairing.find(params[:id])
    @pairing.update_attributes(student_id: current_user.id)
    if @pairing.save
      redirect_to pairings_path
    else
      render 'edit'
    end
  end

  def destroy
    @pairing = Pairing.find(params[:id])
    @pairing.destroy
    redirect_to(:back)
  end

  private

  def pairing_params
    params.require(:pairing).permit(:mentor_id, :student_id, :start_time_text)
  end

end

app/views/pairings/_form.html.erb
<div class='list'>
  <%= form_for (@pairing || pairing) do |f| %>
    <% if making %>
      <%= f.label :start_time_text, 'Start time: ' %>
      <%= f.text_field :start_time_text %><br>
    <% end %>
      <%= f.submit 'Pair', class: 'btn' %>
  <% end %>
</div>

app/views/pairings/_pairing.html.erb
<!-- form to create a new pairing - for mentors only -->

<ul>
  <li>Mentor: <%= pairing.mentor.name %></li>

  <li>Student: <%= display_student(pairing.student) %></li>

  <li>Avg. Rating: <%= display_rating(pairing.mentor) %> </li>
  <li>Phase: <%= pairing.mentor.phase %></li>
  <li><%= pairing.start_time_text %></li>
  <li><%= pairing.mentor.email %></li>
  <li>Mentor Topics: <%= pairing.mentor.show_topics %></li>  <!-- link to email -->

  <% if pairing.mentor_id != current_user.id && pairing.student_id == nil %>
    <%= render partial: 'pairings/form', locals: {making: false, pairing: pairing} %>

    <%#= link_to 'Join this mentor', edit_pairing_path(pairing), class: 'btn-flat minor-button'  %>

  <% end %>
  <% if pairing.start_time < (Time.now).utc.iso8601 && pairing.feedbacks.first.try(:user_id) != current_user.id && pairing.feedbacks.second.try(:user_id) != current_user.id%>
      <%= link_to 'Give Feedback', new_pairing_feedback_path(pairing), class: 'btn-flat minor-button' %><br>
  <% end %>
  <% if pairing.mentor_id == current_user.id && pairing.start_time > (Time.now).utc.iso8601%>
    <%= link_to 'Delete This Pairing', pairing, method: :delete, data: { confirm: 'Are you sure?'}, class: 'btn-flat minor-button' %>
  <% end %>
</ul>

app/views/pairings/edit.html.erb
<%= render partial: 'form', locals: {making: false} %>

app/views/pairings/index.html.erb
<!-- filtered list of upcoming pairings -->
<div class='list'>
  <h1>Available Pairing Sessions</h1>
    <a class="btn" onclick="Materialize.toast('Pete Pairs!', 4000)">What does Pete do?</a>

 <!-- Modal Trigger -->
  <a class="pete waves-effect waves-light btn modal-trigger" href="#modal1">Hi Pete!</a>

  <!-- Modal Structure -->
  <div id="modal1" class="modal">
    <div class="modal-content">
      <h4>Pete has a beard</h4>
      <img src="https://media.licdn.com/mpr/mpr/shrinknp_400_400/AAEAAQAAAAAAAAIwAAAAJGU5YWU1ZmE4LTRiYTUtNDJkNS05MzMyLWM2YWU0ODUzMWRiMw.jpg" alt="Pete" height="750" width="750"><br>
      <img src="https://pbs.twimg.com/media/CtC8t6WUIAEJkOq.jpg" alt="Pete" height="750" width="750"><br>
      <img src="https://pbs.twimg.com/profile_images/710934380173103104/2Y31J86q.jpg" alt="Pete" height="750" width="750"><br>
      <img src="https://assets.about.me/background/users/l/e/o/leongersing_1460940546_71.jpg" alt="Pete" height="750" width="750"><br>
      <img src="https://66.media.tumblr.com/651dd54b0c5ea945eb305ad8ee2ae39c/tumblr_ns5kbntczF1ur7mdeo1_400.gif" alt="Pete" height="750" width="750"><br>Time to Drink!
   </div>
    <div class="modal-footer">
      <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat">Bye Pete</a>
    </div>
  </div>

    <%= render @available_pairings %>
  <% if current_user.phase == 2 || current_user.phase == 3 %>
    <%= link_to 'My Mentor Pairings', user_mentor_path(current_user), class: 'btn'  %><br><br>
  <% end %>
  <%= link_to 'My Student Pairings', user_student_path(current_user), class: 'btn' %>
</div>

app/views/pairings/new.html.erb
<%= render partial: 'form', locals: {making: true} %>