config/routes.rb
Rails.application.routes.draw do
  resources :users, except: :index do
    get 'student'
    get 'mentor'
    resources :topics, only: [:create]
    resources :feedbacks, only: [:index]
  end

  resources :pairings, except: :show do
    resources :feedbacks, only: [:new, :create]
  end

  post '/sessions' => 'sessions#new'
  delete '/sessions' => 'sessions#destroy', as: 'logout'
  root 'users#show'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/css/materialize.min.css">

  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/js/materialize.min.js"></script>
  <title>PetesPairBoard</title>

  <%= csrf_meta_tags %>
</head>
<body>
  <ul class="navbar">
    <li><%= link_to "Home", root_path %></li>
    <% if logged_in? %>
      <li> <%= link_to "Available Pairings", pairings_path %> </li>
      <li> <%= link_to "My Student Pairings", user_student_path(current_user) %> </li>
      <% if current_user.phase == 2 || current_user.phase == 3 %>
        <li> <%= link_to "My Mentor Pairings", user_mentor_path(current_user) %> </li>
        <li> <%= link_to 'Schedule A Pairing', new_pairing_path %> </li>
      <% end %>
    <% else %>
      <li><%= link_to "Login", new_user_path %></li>
      <li><%= link_to "Register", new_user_path %></li>
    <% end %>
    <% if logged_in? %>
        <p class='user-name'> <%= link_to "Hi #{current_user.name.capitalize}!", pairings_path %>' '
          <%= link_to "Logout", logout_path, method: :delete %>
        </p>
    <% end %>
  </ul>

<%= yield %>

</body>
</html>